name: sundlf
services:
  backend:
      build:
        context: ./infra/laravel
        dockerfile: Dockerfile
      container_name: backend-sundlf
      ports:
        - 8000:8000
        - 5173:5173
      volumes:
        - ./laravel:/laravel
        - ./infra/laravel/php.ini:/usr/local/etc/php/php.ini
      tty: true
      stdin_open: true
  mariadb:
    image: mariadb:12
    restart: always
    env_file:
       - ./infra/mariadb/.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./infra/mariadb/my.cnf:/etc/mariadb/conf.d/my.cnf
      - ./infra/mariadb/sql:/docker-entrypoint-initdb.d

volumes:
  mariadb:
    driver: local