name: sundlf
services:
  web:
    image: nginx:latest
    volumes:
      # vueはリバースプロキシでつなげるからマウントしなくて良い
      - ./laravel:/var/www/
      - ./infra/nginx/dev/nginx.conf/:/etc/nginx/nginx.conf:ro
    ports:
      - 8002:80
    environment:
      - NGINX_HOST=localhost

  backend:
    user: "1000:1000"
    build:
      context: ./infra/laravel
      dockerfile: Dockerfile
    container_name: backend-sundlf
    ports:
      - 8000:8000
    volumes:
      - ./laravel:/laravel
      - ./infra/laravel/php.ini:/usr/local/etc/php/php.ini
    tty: true
    stdin_open: true
  mariadb:
    image: mariadb:12
    container_name: mariadb-sundlf
    restart: always
    env_file:
      - ./infra/mariadb/.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./infra/mariadb/my.conf:/etc/mariadb/conf.d/my.cnf
      - ./infra/mariadb/sql:/docker-entrypoint-initdb.d
  frontend:
    user: "1000:1000"
    command: ["npm", "run", "dev"]
    build:
      context: ./infra/vue
      dockerfile: Dockerfile
    container_name: frontend-sundlf
    ports:
      - 5172:5173
      - 6006:6006
    volumes:
      - ./vue:/vue
    tty: true

volumes:
  mariadb:
    driver: local
