[tasks.exec_php]
description = "phpコンテナのdocker execのalias"
run = """
docker compose exec backend bash -ic 
"""

[tasks.exec_vue]
description = "vueコンテナのdocker execのalias"
run = """
docker compose exec vue bash -ic 
"""

# コンテナ名じゃなくてサービス名じゃないといけない


