# マルチバイト文字関係
default_charset = "UTF-8"
mbstring.language = Japanese
mbstring.encoding_translation = Off

# ファイルアップロード
file_uploads = On
upload_max_filesize = 10M
post_max_size = 12M

# 実行時間・メモリ
max_execution_time = 60
memory_limit = 256M

# エラー関係
log_errors = On
error_log = /var/log/php_errors.log

# データベース
; PHP公式の php:8.x-fpm や php:8.x-cli などのイメージでは、pdo_mysql がすでに有効化されているみたい
; extension=pdo_mysql