[mysqld]
# 文字コード設定
# デフォルトを utf8mb4 にすることで、絵文字や日本語も含めて文字化け防止。
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

# タイムゾーン（Laravelと合わせる）
## default-time-zone = 'UTC'

# 接続まわり
## 同時接続数 開発なら 200 くらいで十分らしい
max_connections = 200
## コネクションのアイドル時間。デフォルト（8時間）を維持でOK。
wait_timeout = 28800
interactive_timeout = 28800

# ログ
## 遅いクエリの検出。
slow_query_log = 1
long_query_time = 2
log_error = /var/lib/mysql/mysql-error.log

# InnoDB設定
## テーブルごとにファイルを分ける。パフォーマンス・管理上メリット大。
innodb_file_per_table = 1
## 開発なら 256MB〜512MB くらいで十分。本番はサーバーメモリの 70% 推奨。
innodb_buffer_pool_size = 256M
